sudo: required

services:
  - docker

before_install: 
  - docker build -t azajvahora/docker-react -f Dockerfile.dev .

script: 
  - docker run azajvahora/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWC_SECRET_KEY"

